### PR TITLE
fix: fixes #555 mocha statuses are converted to cypress statuses

### LINKED ISSUE #555: Skipped tests not being shown on dashboard
Please note - issues that are not following the template will be closed automatically:

- [x] I have verified that all sorry-cypress services are running and accessible
- [x] I have read documentation and found no answer to my problem
- [x] I have searched issues / discussions and found to answer to my problem
- [x] I have read [Minio Configutation guide](https://docs.sorry-cypress.dev/configuration/director-configuration/minio-configuration) - for issues related to Screenshots / Videos uploads for Minio 
- [ ] I have activated the debug mode `DEBUG=cypress:server:api cy2 ....` and have the network error

## Summary

Sorry cypress doesn't show skipped tests in the run summary

## How to reproduce

1. Run a spec that skips tests
2. Check run result in dashboard

## Relevant logs / screenshots

- Please submit relevant logs from `DEBUG=cypress:server:api cy2 ....`
- Please submit relevant logs from director / api / dahsboard service

*Director logs from the beginning until end of the run*
```
2022-03-22T12:09:54.683813260Z {"level":30,"time":1647950994682,"requestId":"4ddad1e9-6bab-4361-bfc4-1b1cb85a4f75","ci":{"params":null,"provider":null},"specs":["cypress/integration/flows/B2BRegistrationES.spec.ts"],"commit":{"sha":"cd706f27e57746ff25e73ded68ef5ac3f264407d","branch":"feature/COPS-4179-add-more-cypress-suites-to-pipeline","authorName":"jtrivino","authorEmail":"j.trivinomonedero@metro-markets.de","message":"Merge branch 'main' into feature/COPS-4179-add-more-cypress-suites-to-pipeline\n","remoteOrigin":"ssh://git@git.cps.metro-markets.org:4022/mpdev/monorepo.git","defaultBranch":null},"group":null,"platform":{"osCpus":[{"model":"Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz","speed":2900,"times":{"user":22731850,"nice":28100,"sys":5247820,"idle":105208270,"irq":0}},{"model":"Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz","speed":2900,"times":{"user":21621130,"nice":22040,"sys":5744350,"idle":8229530,"irq":0}},{"model":"Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz","speed":2900,"times":{"user":22599580,"nice":23450,"sys":5289180,"idle":8210890,"irq":0}},{"model":"Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz","speed":2970,"times":{"user":22869970,"nice":27710,"sys":5414810,"idle":8128690,"irq":0}}],"osName":"linux","osMemory":{"free":195092480,"total":20719685632},"osVersion":"Ubuntu - 21.10","browserName":"Electron","browserVersion":"94.0.4606.81"},"parallel":null,"ciBuildId":null,"projectId":"preprod","recordKey":"ByGPwZmGdNxrpV9Z","specPattern":"cypress/integration/flows/B2BRegistrationES.spec.ts","tags":[""[],"testingType":"e2e","runnerCapabilities":{"dynamicSpecsInSerialMode":true,"skipSpecAction":true},"host":"director.cypress.cps.metro-markets.org","x-request-id":"85cee41d11bad7c82e93699312eeac3c","x-real-ip":"185.171.218.132","x-forwarded-for":"185.171.218.132","x-forwarded-host":"director.cypress.cps.metro-markets.org","x-forwarded-port":"443","x-forwarded-proto":"https","x-forwarded-scheme":"https","x-scheme":"https","content-length":"1516","x-route-version":"4","x-cypress-request-attempt":"0","x-os-name":"linux","x-cypress-version":"9.5.2","accept-encoding":"gzip, deflate","accept":"application/json","content-type":"application/json","msg":"New machine is requesting to create a run"}
2022-03-22T12:09:54.836553156Z {"level":30,"time":1647950994835,"requestId":"4ddad1e9-6bab-4361-bfc4-1b1cb85a4f75","groupId":"sorry-unknown","machineId":"307deb93-a583-495a-b801-7b1d398e89c1","runId":"eaae3e7c456d2997e4dcf4f99e17f91e","runUrl":"https://dashboard.cypress.cps.metro-markets.org/run/eaae3e7c456d2997e4dcf4f99e17f91e","isNewRun":false,"warnings":[],"msg":"Responding to machine"}
2022-03-22T12:09:54.837039136Z {"level":30,"time":1647950994836,"req":{"id":1404,"method":"POST","url":"/runs","query":{},"params":{},"headers":{"host":"director.cypress.cps.metro-markets.org","x-request-id":"85cee41d11bad7c82e93699312eeac3c","x-real-ip":"185.171.218.132","x-forwarded-for":"185.171.218.132","x-forwarded-host":"director.cypress.cps.metro-markets.org","x-forwarded-port":"443","x-forwarded-proto":"https","x-forwarded-scheme":"https","x-scheme":"https","content-length":"1516","x-route-version":"4","x-cypress-request-attempt":"0","x-os-name":"linux","x-cypress-version":"9.5.2","accept-encoding":"gzip, deflate","accept":"application/json","content-type":"application/json"},"remoteAddress":"::ffff:172.20.72.5","remotePort":43490},"res":{"statusCode":200,"headers":{"x-powered-by":"Express","content-type":"application/json; charset=utf-8","content-length":"248","etag":"W/\"f8-Cil4t1JBzD6NRemo6cXsqVcowks\""}},"responseTime":155,"msg":"request completed"}
2022-03-22T12:09:55.203708332Z {"level":30,"time":1647950995202,"requestId":"cd689ca2-2457-4c95-b9b5-107aef0f9eec","spec":null,"groupId":"sorry-unknown","machineId":"307deb93-a583-495a-b801-7b1d398e89c1","platform":{"osCpus":[{"model":"Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz","speed":2900,"times":{"user":22731850,"nice":28100,"sys":5247820,"idle":105208270,"irq":0}},{"model":"Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz","speed":2900,"times":{"user":21621130,"nice":22040,"sys":5744350,"idle":8229530,"irq":0}},{"model":"Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz","speed":2900,"times":{"user":22599580,"nice":23450,"sys":5289180,"idle":8210890,"irq":0}},{"model":"Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz","speed":2970,"times":{"user":22869970,"nice":27710,"sys":5414810,"idle":8128690,"irq":0}}],"osName":"linux","osMemory":{"free":195092480,"total":20719685632},"osVersion":"Ubuntu - 21.10","browserName":"Electron","browserVersion":"94.0.4606.81"},"host":"director.cypress.cps.metro-markets.org","x-request-id":"1991d113330e22c183ebd1c9c5163252","x-real-ip":"185.171.218.132","x-forwarded-for":"185.171.218.132","x-forwarded-host":"director.cypress.cps.metro-markets.org","x-forwarded-port":"443","x-forwarded-proto":"https","x-forwarded-scheme":"https","x-scheme":"https","content-length":"837","x-route-version":"5","x-cypress-run-id":"eaae3e7c456d2997e4dcf4f99e17f91e","x-cypress-request-attempt":"0","x-os-name":"linux","x-cypress-version":"9.5.2","accept-encoding":"gzip, deflate","accept":"application/json","content-type":"application/json","msg":"Machine is requesting a new task"}
2022-03-22T12:09:55.203812179Z {"level":30,"time":1647950995202,"requestId":"cd689ca2-2457-4c95-b9b5-107aef0f9eec","runId":"eaae3e7c456d2997e4dcf4f99e17f91e","groupId":"sorry-unknown","machineId":"307deb93-a583-495a-b801-7b1d398e89c1","cypressVersion":"9.5.2","msg":"Getting the next unclaimed spec"}
2022-03-22T12:09:55.205541999Z {"level":30,"time":1647950995204,"requestId":"cd689ca2-2457-4c95-b9b5-107aef0f9eec","runId":"eaae3e7c456d2997e4dcf4f99e17f91e","groupId":"sorry-unknown","machineId":"307deb93-a583-495a-b801-7b1d398e89c1","cypressVersion":"9.5.2","msg":"No more unclaimed specs"}
2022-03-22T12:09:55.205652004Z {"level":30,"time":1647950995204,"requestId":"cd689ca2-2457-4c95-b9b5-107aef0f9eec","runId":"eaae3e7c456d2997e4dcf4f99e17f91e","machineId":"307deb93-a583-495a-b801-7b1d398e89c1","groupId":"sorry-unknown","task":{"instance":null,"claimedInstances":0,"totalInstances":1,"projectId":"preprod"},"msg":"All spec files claimed, nothing to run"}
2022-03-22T12:09:55.206046143Z {"level":30,"time":1647950995205,"req":{"id":1405,"method":"POST","url":"/runs/eaae3e7c456d2997e4dcf4f99e17f91e/instances","query":{},"params":{},"headers":{"host":"director.cypress.cps.metro-markets.org","x-request-id":"1991d113330e22c183ebd1c9c5163252","x-real-ip":"185.171.218.132","x-forwarded-for":"185.171.218.132","x-forwarded-host":"director.cypress.cps.metro-markets.org","x-forwarded-port":"443","x-forwarded-proto":"https","x-forwarded-scheme":"https","x-scheme":"https","content-length":"837","x-route-version":"5","x-cypress-run-id":"eaae3e7c456d2997e4dcf4f99e17f91e","x-cypress-request-attempt":"0","x-os-name":"linux","x-cypress-version":"9.5.2","accept-encoding":"gzip, deflate","accept":"application/json","content-type":"application/json"},"remoteAddress":"::ffff:172.20.78.5","remotePort":49946},"res":{"statusCode":200,"headers":{"x-powered-by":"Express","content-type":"application/json; charset=utf-8","content-length":"71","etag":"W/\"47-tN9nHK5ZDMHUI9D4SvGg7tjLPyU\""}},"responseTime":3,"msg":"request completed"}
2022-03-22T12:10:49.257147497Z {"level":30,"time":1647951049256,"requestId":"4aa72233-a461-488d-8b6c-3ade570d1880","ci":{"params":null,"provider":null},"specs":["cypress/integration/flows/B2BRegistrationES.spec.ts"],"commit":{"sha":"cd706f27e57746ff25e73ded68ef5ac3f264407d","branch":"feature/COPS-4179-add-more-cypress-suites-to-pipeline","authorName":"jtrivino","authorEmail":"j.trivinomonedero@metro-markets.de","message":"Merge branch 'main' into feature/COPS-4179-add-more-cypress-suites-to-pipeline\n","remoteOrigin":"ssh://git@git.cps.metro-markets.org:4022/mpdev/monorepo.git","defaultBranch":null},"group":null,"platform":{"osCpus":[{"model":"Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz","speed":3294,"times":{"user":22751420,"nice":28110,"sys":5253670,"idle":105236430,"irq":0}},{"model":"Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz","speed":3294,"times":{"user":21640400,"nice":22040,"sys":5750300,"idle":8257270,"irq":0}},{"model":"Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz","speed":3285,"times":{"user":22619500,"nice":23480,"sys":5294690,"idle":8238770,"irq":0}},{"model":"Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz","speed":3288,"times":{"user":22891340,"nice":27720,"sys":5420860,"idle":8154910,"irq":0}}],"osName":"linux","osMemory":{"free":226234368,"total":20719685632},"osVersion":"Ubuntu - 21.10","browserName":"Electron","browserVersion":"94.0.4606.81"},"parallel":null,"ciBuildId":null,"projectId":"preprod","recordKey":"ByGPwZmGdNxrpV9Z","specPattern":"cypress/integration/flows/B2BRegistrationES.spec.ts","tags":[""[],"testingType":"e2e","runnerCapabilities":{"dynamicSpecsInSerialMode":true,"skipSpecAction":true},"host":"director.cypress.cps.metro-markets.org","x-request-id":"1fd1d7720a379210fd3fe1afdc4231c4","x-real-ip":"185.171.218.132","x-forwarded-for":"185.171.218.132","x-forwarded-host":"director.cypress.cps.metro-markets.org","x-forwarded-port":"443","x-forwarded-proto":"https","x-forwarded-scheme":"https","x-scheme":"https","content-length":"1516","x-route-version":"4","x-cypress-request-attempt":"0","x-os-name":"linux","x-cypress-version":"9.5.2","accept-encoding":"gzip, deflate","accept":"application/json","content-type":"application/json","msg":"New machine is requesting to create a run"}
2022-03-22T12:10:49.285646354Z {"level":30,"time":1647951049284,"requestId":"4aa72233-a461-488d-8b6c-3ade570d1880","groupId":"sorry-unknown","machineId":"85735bae-93ac-4051-8882-a41df2e5e3ca","runId":"eaae3e7c456d2997e4dcf4f99e17f91e","runUrl":"https://dashboard.cypress.cps.metro-markets.org/run/eaae3e7c456d2997e4dcf4f99e17f91e","isNewRun":false,"warnings":[],"msg":"Responding to machine"}
2022-03-22T12:10:49.286189583Z {"level":30,"time":1647951049285,"req":{"id":1406,"method":"POST","url":"/runs","query":{},"params":{},"headers":{"host":"director.cypress.cps.metro-markets.org","x-request-id":"1fd1d7720a379210fd3fe1afdc4231c4","x-real-ip":"185.171.218.132","x-forwarded-for":"185.171.218.132","x-forwarded-host":"director.cypress.cps.metro-markets.org","x-forwarded-port":"443","x-forwarded-proto":"https","x-forwarded-scheme":"https","x-scheme":"https","content-length":"1516","x-route-version":"4","x-cypress-request-attempt":"0","x-os-name":"linux","x-cypress-version":"9.5.2","accept-encoding":"gzip, deflate","accept":"application/json","content-type":"application/json"},"remoteAddress":"::ffff:172.20.72.5","remotePort":44720},"res":{"statusCode":200,"headers":{"x-powered-by":"Express","content-type":"application/json; charset=utf-8","content-length":"248","etag":"W/\"f8-mzpFG1Mp+4C3+AkHKDYpl1zVqcg\""}},"responseTime":32,"msg":"request completed"}
2022-03-22T12:10:49.790182528Z {"level":30,"time":1647951049788,"requestId":"89926149-1b23-4b52-8b98-3c391b4b6a8a","spec":null,"groupId":"sorry-unknown","machineId":"85735bae-93ac-4051-8882-a41df2e5e3ca","platform":{"osCpus":[{"model":"Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz","speed":3294,"times":{"user":22751420,"nice":28110,"sys":5253670,"idle":105236430,"irq":0}},{"model":"Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz","speed":3294,"times":{"user":21640400,"nice":22040,"sys":5750300,"idle":8257270,"irq":0}},{"model":"Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz","speed":3285,"times":{"user":22619500,"nice":23480,"sys":5294690,"idle":8238770,"irq":0}},{"model":"Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz","speed":3288,"times":{"user":22891340,"nice":27720,"sys":5420860,"idle":8154910,"irq":0}}],"osName":"linux","osMemory":{"free":226234368,"total":20719685632},"osVersion":"Ubuntu - 21.10","browserName":"Electron","browserVersion":"94.0.4606.81"},"host":"director.cypress.cps.metro-markets.org","x-request-id":"afb9b1290affec22ae59a4b256a2c013","x-real-ip":"185.171.218.132","x-forwarded-for":"185.171.218.132","x-forwarded-host":"director.cypress.cps.metro-markets.org","x-forwarded-port":"443","x-forwarded-proto":"https","x-forwarded-scheme":"https","x-scheme":"https","content-length":"837","x-route-version":"5","x-cypress-run-id":"eaae3e7c456d2997e4dcf4f99e17f91e","x-cypress-request-attempt":"0","x-os-name":"linux","x-cypress-version":"9.5.2","accept-encoding":"gzip, deflate","accept":"application/json","content-type":"application/json","msg":"Machine is requesting a new task"}
2022-03-22T12:10:49.790267540Z {"level":30,"time":1647951049788,"requestId":"89926149-1b23-4b52-8b98-3c391b4b6a8a","runId":"eaae3e7c456d2997e4dcf4f99e17f91e","groupId":"sorry-unknown","machineId":"85735bae-93ac-4051-8882-a41df2e5e3ca","cypressVersion":"9.5.2","msg":"Getting the next unclaimed spec"}
2022-03-22T12:10:49.799382344Z {"level":30,"time":1647951049798,"requestId":"89926149-1b23-4b52-8b98-3c391b4b6a8a","runId":"eaae3e7c456d2997e4dcf4f99e17f91e","groupId":"sorry-unknown","machineId":"85735bae-93ac-4051-8882-a41df2e5e3ca","cypressVersion":"9.5.2","spec":{"spec":"cypress/integration/flows/B2BRegistrationES.spec.ts","instanceId":"414ea346-066e-4b97-b5ec-d4a35e316046","claimedAt":null,"completedAt":null,"groupId":"sorry-unknown","machineId":null,"results":null},"msg":"Received unclaimed spec, setting spec as claimed"}
2022-03-22T12:10:49.799449518Z {"level":30,"time":1647951049798,"requestId":"89926149-1b23-4b52-8b98-3c391b4b6a8a","runId":"eaae3e7c456d2997e4dcf4f99e17f91e","groupId":"sorry-unknown","instanceId":"414ea346-066e-4b97-b5ec-d4a35e316046","machineId":"85735bae-93ac-4051-8882-a41df2e5e3ca","msg":"Setting spec as claimed"}
2022-03-22T12:10:49.815545025Z {"level":30,"time":1647951049814,"requestId":"89926149-1b23-4b52-8b98-3c391b4b6a8a","runId":"eaae3e7c456d2997e4dcf4f99e17f91e","groupId":"sorry-unknown","instanceId":"414ea346-066e-4b97-b5ec-d4a35e316046","machineId":"85735bae-93ac-4051-8882-a41df2e5e3ca","msg":"Success setting spec as claimed"}
2022-03-22T12:10:49.842426243Z {"level":30,"time":1647951049841,"requestId":"89926149-1b23-4b52-8b98-3c391b4b6a8a","instance":{"spec":"cypress/integration/flows/B2BRegistrationES.spec.ts","instanceId":"414ea346-066e-4b97-b5ec-d4a35e316046","claimedAt":null,"completedAt":null,"groupId":"sorry-unknown","machineId":null,"results":null},"claimedInstances":1,"totalInstances":1,"projectId":"preprod","msg":"Detected first claimed instance for group"}
2022-03-22T12:10:49.842499614Z {"level":30,"time":1647951049841,"requestId":"89926149-1b23-4b52-8b98-3c391b4b6a8a","spec":"cypress/integration/flows/B2BRegistrationES.spec.ts","instanceId":"414ea346-066e-4b97-b5ec-d4a35e316046","claimedAt":null,"completedAt":null,"groupId":"sorry-unknown","machineId":"85735bae-93ac-4051-8882-a41df2e5e3ca","results":null,"cypressVersion":"9.5.2","msg":"Sending a new instance to machine"}
2022-03-22T12:10:49.844093018Z {"level":30,"time":1647951049842,"req":{"id":1407,"method":"POST","url":"/runs/eaae3e7c456d2997e4dcf4f99e17f91e/instances","query":{},"params":{},"headers":{"host":"director.cypress.cps.metro-markets.org","x-request-id":"afb9b1290affec22ae59a4b256a2c013","x-real-ip":"185.171.218.132","x-forwarded-for":"185.171.218.132","x-forwarded-host":"director.cypress.cps.metro-markets.org","x-forwarded-port":"443","x-forwarded-proto":"https","x-forwarded-scheme":"https","x-scheme":"https","content-length":"837","x-route-version":"5","x-cypress-run-id":"eaae3e7c456d2997e4dcf4f99e17f91e","x-cypress-request-attempt":"0","x-os-name":"linux","x-cypress-version":"9.5.2","accept-encoding":"gzip, deflate","accept":"application/json","content-type":"application/json"},"remoteAddress":"::ffff:172.20.78.5","remotePort":51840},"res":{"statusCode":200,"headers":{"x-powered-by":"Express","content-type":"application/json; charset=utf-8","content-length":"154","etag":"W/\"9a-0jktCT+z31I9hutz3TYR3106JCM\""}},"responseTime":54,"msg":"request completed"}
2022-03-22T12:10:49.864254654Z {"level":30,"time":1647951049863,"requestId":"89926149-1b23-4b52-8b98-3c391b4b6a8a","runId":"eaae3e7c456d2997e4dcf4f99e17f91e","groupId":"sorry-unknown","spec":"cypress/integration/flows/B2BRegistrationES.spec.ts","eventType":"INSTANCE_START","msg":"[hooks[] Reporting INSTANCE_START for eaae3e7c456d2997e4dcf4f99e17f91e..."}
2022-03-22T12:10:49.864731286Z {"level":30,"time":1647951049864,"requestId":"89926149-1b23-4b52-8b98-3c391b4b6a8a","runId":"eaae3e7c456d2997e4dcf4f99e17f91e","groupId":"sorry-unknown","projectId":"preprod","eventType":"RUN_START","msg":"[hooks[] Reporting RUN_START for eaae3e7c456d2997e4dcf4f99e17f91e..."}
2022-03-22T12:10:53.058288312Z {"level":30,"time":1647951053057,"requestId":"614b2c57-aad2-470a-9f7b-47077c3aa970","instanceId":"414ea346-066e-4b97-b5ec-d4a35e316046","msg":"Received instance tests"}
2022-03-22T12:10:53.059621675Z {"level":30,"time":1647951053059,"requestId":"614b2c57-aad2-470a-9f7b-47077c3aa970","instanceId":"414ea346-066e-4b97-b5ec-d4a35e316046","runId":"eaae3e7c456d2997e4dcf4f99e17f91e","groupId":"sorry-unknown","msg":"Setting instance tests"}
2022-03-22T12:10:53.069022638Z {"level":30,"time":1647951053068,"requestId":"614b2c57-aad2-470a-9f7b-47077c3aa970","instanceId":"414ea346-066e-4b97-b5ec-d4a35e316046","runId":"eaae3e7c456d2997e4dcf4f99e17f91e","groupId":"sorry-unknown","msg":"Updating group progress"}
2022-03-22T12:10:53.074056543Z {"level":30,"time":1647951053073,"req":{"id":1408,"method":"POST","url":"/instances/414ea346-066e-4b97-b5ec-d4a35e316046/tests","query":{},"params":{},"headers":{"host":"director.cypress.cps.metro-markets.org","x-request-id":"35ff598ffbf73614a641302d3dc19d70","x-real-ip":"185.171.218.132","x-forwarded-for":"185.171.218.132","x-forwarded-host":"director.cypress.cps.metro-markets.org","x-forwarded-port":"443","x-forwarded-proto":"https","x-forwarded-scheme":"https","x-scheme":"https","content-length":"17955","x-route-version":"1","x-cypress-run-id":"eaae3e7c456d2997e4dcf4f99e17f91e","x-cypress-request-attempt":"0","x-os-name":"linux","x-cypress-version":"9.5.2","accept-encoding":"gzip, deflate","accept":"application/json","content-type":"application/json"},"remoteAddress":"::ffff:172.20.73.6","remotePort":50806},"res":{"statusCode":200,"headers":{"x-powered-by":"Express","content-type":"application/json; charset=utf-8","content-length":"2","etag":"W/\"2-vyGp6PvFo4RvsFtPoIWeCReyIC8\""}},"responseTime":17,"msg":"request completed"}
2022-03-22T12:12:32.073788720Z {"level":30,"time":1647951152072,"requestId":"5e40c79f-b00c-4e84-aa70-a33017addeae","instanceId":"414ea346-066e-4b97-b5ec-d4a35e316046","stats":{"suites":1,"tests":2,"passes":0,"pending":0,"skipped":2,"failures":0,"wallClockStartedAt":"2022-03-22T12:10:53.173Z","wallClockEndedAt":"2022-03-22T12:12:31.482Z","wallClockDuration":98309},"tests":[{"clientId":"r3","state":"skipped","displayError":null,"attempts":[{"state":"skipped","error":null,"timings":{"lifecycle":83,"before all":[{"hookId":"h3","fnDuration":1229,"afterFnDuration":1}]},"failedFromHookId":null,"wallClockStartedAt":"2022-03-22T12:10:58.089Z","wallClockDuration":null,"videoTimestamp":null}]},{"clientId":"r4","state":"skipped","displayError":null,"attempts":[{"state":"skipped","error":null,"timings":null,"failedFromHookId":null,"wallClockStartedAt":null,"wallClockDuration":null,"videoTimestamp":null}]}],"exception":null,"video":false,"screenshots":[{"screenshotId":"p9x4b","name":null,"testId":"r3","testAttemptIndex":0,"takenAt":"2022-03-22T12:12:30.943Z","height":720,"width":1280}],"reporterStats":{"suites":1,"tests":0,"passes":0,"pending":0,"failures":0,"start":"2022-03-22T12:10:53.183Z","end":"2022-03-22T12:12:31.732Z","duration":98549},"metadata":{"studioCreated":0,"studioExtended":0},"msg":"Received instance results"}
2022-03-22T12:12:32.077760663Z {"level":30,"time":1647951152077,"requestId":"5e40c79f-b00c-4e84-aa70-a33017addeae","instanceId":"414ea346-066e-4b97-b5ec-d4a35e316046","runId":"eaae3e7c456d2997e4dcf4f99e17f91e","groupId":"sorry-unknown","msg":"Setting instance results"}
2022-03-22T12:12:32.090848035Z {"level":30,"time":1647951152090,"requestId":"5e40c79f-b00c-4e84-aa70-a33017addeae","instanceId":"414ea346-066e-4b97-b5ec-d4a35e316046","screenshotUploadUrls":[{"readUrl":"https://storage.googleapis.com:443/cps-sorry-cypress-assets/249028b3032c0b9855aa2664e584c1d3.png","uploadUrl":"https://minio.cypress.cps.metro-markets.org/cps-sorry-cypress-assets/249028b3032c0b9855aa2664e584c1d3.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=lViwuJHy9cXImTxc20F9%2F20220322%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220322T121232Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=46c930aff597b6e91324e209cd16f5c09a18eb6d833bd3ceab41f63ec09de4f4","screenshotId":"p9x4b"}],"videoUploadInstructions":null,"msg":"Sending assets upload URLs"}
2022-03-22T12:12:32.091758104Z {"level":30,"time":1647951152091,"req":{"id":1409,"method":"POST","url":"/instances/414ea346-066e-4b97-b5ec-d4a35e316046/results","query":{},"params":{},"headers":{"host":"director.cypress.cps.metro-markets.org","x-request-id":"9eba589776025b48ab3f4240d2dc8b50","x-real-ip":"185.171.218.132","x-forwarded-for":"185.171.218.132","x-forwarded-host":"director.cypress.cps.metro-markets.org","x-forwarded-port":"443","x-forwarded-proto":"https","x-forwarded-scheme":"https","x-scheme":"https","content-length":"1133","x-route-version":"1","x-cypress-request-attempt":"0","x-os-name":"linux","x-cypress-version":"9.5.2","accept-encoding":"gzip, deflate","accept":"application/json","content-type":"application/json"},"remoteAddress":"::ffff:172.20.73.6","remotePort":53794},"res":{"statusCode":200,"headers":{"x-powered-by":"Express","content-type":"application/json; charset=utf-8","content-length":"549","etag":"W/\"225-7je2Yp5hkkmd1DfhGPy3DSEIpHw\""}},"responseTime":19,"msg":"request completed"}
2022-03-22T12:12:32.099590271Z {"level":30,"time":1647951152098,"requestId":"5e40c79f-b00c-4e84-aa70-a33017addeae","runId":"eaae3e7c456d2997e4dcf4f99e17f91e","groupId":"sorry-unknown","spec":"cypress/integration/flows/B2BRegistrationES.spec.ts","eventType":"INSTANCE_FINISH","msg":"[hooks[] Reporting INSTANCE_FINISH for eaae3e7c456d2997e4dcf4f99e17f91e..."}
2022-03-22T12:12:35.101376056Z {"level":30,"time":1647951155100,"requestId":"5e40c79f-b00c-4e84-aa70-a33017addeae","runId":"eaae3e7c456d2997e4dcf4f99e17f91e","msg":"[run-completion[] Run completed"}
2022-03-22T12:12:35.104425046Z {"level":30,"time":1647951155103,"requestId":"5e40c79f-b00c-4e84-aa70-a33017addeae","runId":"eaae3e7c456d2997e4dcf4f99e17f91e","groupId":"sorry-unknown","eventType":"RUN_FINISH","msg":"[hooks[] Reporting RUN_FINISH for eaae3e7c456d2997e4dcf4f99e17f91e..."}
2022-03-22T12:12:39.539153234Z {"level":30,"time":1647951159538,"requestId":"ae60d957-5356-481f-8593-904f3ddad86c","instanceId":"414ea346-066e-4b97-b5ec-d4a35e316046","msg":"[not implemented[] Received stdout for instance"}
2022-03-22T12:12:39.539797150Z {"level":30,"time":1647951159538,"req":{"id":1410,"method":"PUT","url":"/instances/414ea346-066e-4b97-b5ec-d4a35e316046/stdout","query":{},"params":{},"headers":{"host":"director.cypress.cps.metro-markets.org","x-request-id":"b211509faf2f381474e925d8a6cacf3b","x-real-ip":"185.171.218.132","x-forwarded-for":"185.171.218.132","x-forwarded-host":"director.cypress.cps.metro-markets.org","x-forwarded-port":"443","x-forwarded-proto":"https","x-forwarded-scheme":"https","x-scheme":"https","content-length":"10228","x-cypress-request-attempt":"0","x-os-name":"linux","x-cypress-version":"9.5.2","accept-encoding":"gzip, deflate","accept":"application/json","content-type":"application/json"},"remoteAddress":"::ffff:172.20.72.5","remotePort":46602},"res":{"statusCode":200,"headers":{"x-powered-by":"Express","content-type":"text/plain; charset=utf-8","content-length":"2","etag":"W/\"2-nOO9QiTIwXgNtWtBJezz8kv3SLc\""}},"responseTime":1,"msg":"request completed"}
2022-03-22T12:12:39.833226108Z {"level":30,"time":1647951159832,"requestId":"7d19739b-9313-400c-a738-1913845a6265","spec":null,"groupId":"sorry-unknown","machineId":"85735bae-93ac-4051-8882-a41df2e5e3ca","platform":{"osCpus":[{"model":"Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz","speed":3294,"times":{"user":22751420,"nice":28110,"sys":5253670,"idle":105236430,"irq":0}},{"model":"Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz","speed":3294,"times":{"user":21640400,"nice":22040,"sys":5750300,"idle":8257270,"irq":0}},{"model":"Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz","speed":3285,"times":{"user":22619500,"nice":23480,"sys":5294690,"idle":8238770,"irq":0}},{"model":"Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz","speed":3288,"times":{"user":22891340,"nice":27720,"sys":5420860,"idle":8154910,"irq":0}}],"osName":"linux","osMemory":{"free":226234368,"total":20719685632},"osVersion":"Ubuntu - 21.10","browserName":"Electron","browserVersion":"94.0.4606.81"},"host":"director.cypress.cps.metro-markets.org","x-request-id":"7b454fd4d67f4355ab151a0facb60d71","x-real-ip":"185.171.218.132","x-forwarded-for":"185.171.218.132","x-forwarded-host":"director.cypress.cps.metro-markets.org","x-forwarded-port":"443","x-forwarded-proto":"https","x-forwarded-scheme":"https","x-scheme":"https","content-length":"837","x-route-version":"5","x-cypress-run-id":"eaae3e7c456d2997e4dcf4f99e17f91e","x-cypress-request-attempt":"0","x-os-name":"linux","x-cypress-version":"9.5.2","accept-encoding":"gzip, deflate","accept":"application/json","content-type":"application/json","msg":"Machine is requesting a new task"}
2022-03-22T12:12:39.833334528Z {"level":30,"time":1647951159832,"requestId":"7d19739b-9313-400c-a738-1913845a6265","runId":"eaae3e7c456d2997e4dcf4f99e17f91e","groupId":"sorry-unknown","machineId":"85735bae-93ac-4051-8882-a41df2e5e3ca","cypressVersion":"9.5.2","msg":"Getting the next unclaimed spec"}
2022-03-22T12:12:39.836055414Z {"level":30,"time":1647951159835,"requestId":"7d19739b-9313-400c-a738-1913845a6265","runId":"eaae3e7c456d2997e4dcf4f99e17f91e","groupId":"sorry-unknown","machineId":"85735bae-93ac-4051-8882-a41df2e5e3ca","cypressVersion":"9.5.2","msg":"No more unclaimed specs"}
2022-03-22T12:12:39.836166022Z {"level":30,"time":1647951159835,"requestId":"7d19739b-9313-400c-a738-1913845a6265","runId":"eaae3e7c456d2997e4dcf4f99e17f91e","machineId":"85735bae-93ac-4051-8882-a41df2e5e3ca","groupId":"sorry-unknown","task":{"instance":null,"claimedInstances":0,"totalInstances":1,"projectId":"preprod"},"msg":"All spec files claimed, nothing to run"}
2022-03-22T12:12:39.836380815Z {"level":30,"time":1647951159835,"req":{"id":1411,"method":"POST","url":"/runs/eaae3e7c456d2997e4dcf4f99e17f91e/instances","query":{},"params":{},"headers":{"host":"director.cypress.cps.metro-markets.org","x-request-id":"7b454fd4d67f4355ab151a0facb60d71","x-real-ip":"185.171.218.132","x-forwarded-for":"185.171.218.132","x-forwarded-host":"director.cypress.cps.metro-markets.org","x-forwarded-port":"443","x-forwarded-proto":"https","x-forwarded-scheme":"https","x-scheme":"https","content-length":"837","x-route-version":"5","x-cypress-run-id":"eaae3e7c456d2997e4dcf4f99e17f91e","x-cypress-request-attempt":"0","x-os-name":"linux","x-cypress-version":"9.5.2","accept-encoding":"gzip, deflate","accept":"application/json","content-type":"application/json"},"remoteAddress":"::ffff:172.20.73.6","remotePort":53934},"res":{"statusCode":200,"headers":{"x-powered-by":"Express","content-type":"application/json; charset=utf-8","content-length":"71","etag":"W/\"47-tN9nHK5ZDMHUI9D4SvGg7tjLPyU\""}},"responseTime":4,"msg":"request completed"}
2022-03-22T12:15:57.637445480Z {"level":30,"time":1647951357636,"runId":"5586590a8d20a478a7978ee7faba9578","msg":"[run-completion[] Run completed"}
```

- Please submit screenshots if relevant

*Job failed, but no skipped tests shown*
image

*2 skipped tests, but not showing on the icon bar*
image

*cypress logs shows skipped tests, but dashboard doesn't*
image
image

## Environment

- sorry-cypress version: `2.1.1`
- cypress version: `9.5.2`
- platform: `docker / helm chart`
- service: `director | dashboard`

### PR DESCRIPTION
**Pull request by Aeolun**
This modifies the code in the director that receives statuses from cypress, and converts those statuses to something that makes sense in the sorry-cypress interface.

This is relation to the issues described in #555, but also my own issues trying to query the sorry cypress API and getting a whole bunch of pending tests back when my tests are already complete.

When directory receives the following statuses from cypress they're converted:

- `pending`: converted into `skipped`
- `skipped`: converted into `failed`, this should really remain 'skipped', but I can't make a distinction between error-skipped, and desired skipped

This will result in the interface never displaying any pending tests if the instance has completed.

It also adds display for total number of tests per instance/run/tests pretty much anywhere in the interface. There is still some discrepancy somewhere between what `setInstanceTests` reports initially, and what is later returned as the total by `updateInstanceResults`, but I haven't been able to figure out why that is.

### CODE REVIEW

File: packages/dashboard/src/run/runSummary/runSummary.tsx [hunk 1]
```diff
@@ -23,6 +23,17 @@ import { RunStartTime } from '../runStartTime';
...
+  if (!specs) return undefined;
+  let total = 0;
+
+  specs.forEach((spec) => {
+    total += spec.results?.stats?.tests ?? 0;
+  });
+
+  return total;
+}
+
```
Comment (ImanMahmoudinasab) [inline packages/dashboard/src/run/runSummary/runSummary.tsx:36]: I can't see this function is referenced anywhere. Do we need it?

**Review by ImanMahmoudinasab — APPROVED** [review]

File: packages/dashboard/src/run/runSummary/runSummary.tsx (hunk 1 above)
Comment (Aeolun) [reply packages/dashboard/src/run/runSummary/runSummary.tsx:36]: @ImanMahmoudinasab You are correct, it's a remainder of when I was trying to figure out why the total eventually reported results differed from what cypress initially tells it's going to execute.
